server:
  port:8081


rand:
  client:
    address:
      url: http://localhost:8082/addresses

spring:
  cloud:
    openfeign:
      client:
        config:
          FindAddressByZipCodeClient:
            url: http://localhost:8082/addresses
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
